### ISSUE TITLE
Game crash at startup

### ISSUE THREAD

**Issue by RusticMaple** [KosmosPrime/OpenComputers#20]
The newest version currently in the release tab seems to be crashing for me at boot.
It might be because to me running linux instead of windows because nobody seems to have reported this issue here before me.

the crash report looks as such:

```

java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
	at li.cil.oc.client.renderer.font.FontParserHex.getGlyph(FontParserHex.java:111) ~[opencomputers:MC1.16.5-1.8.5.3+0a4e918b6] {re:classloading}
	at li.cil.oc.client.renderer.font.DynamicFontRenderer.createCharIcon(DynamicFontRenderer.scala:97) ~[opencomputers:MC1.16.5-1.8.5.3+0a4e918b6] {re:classloading}
	at li.cil.oc.client.renderer.font.DynamicFontRenderer.$anonfun$generateChar$1(DynamicFontRenderer.scala:79) ~[opencomputers:MC1.16.5-1.8.5.3+0a4e918b6] {re:classloading}
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:454) ~[?:?] {re:classloading}
	at li.cil.oc.client.renderer.font.DynamicFontRenderer.generateChar(DynamicFontRenderer.scala:79) ~[opencomputers:MC1.16.5-1.8.5.3+0a4e918b6] {re:classloading}
	at li.cil.oc.client.renderer.font.TextureFontRenderer.$anonfun$generateChars$1(TextureFontRenderer.scala:36) ~[opencomputers:MC1.16.5-1.8.5.3+0a4e918b6] {re:classloading}
	at li.cil.oc.client.renderer.font.TextureFontRenderer.$anonfun$generateChars$1$adapted(TextureFontRenderer.scala:35) ~[opencomputers:MC1.16.5-1.8.5.3+0a4e918b6] {re:classloading}
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1328) ~[?:?] {re:classloading}
	at li.cil.oc.client.renderer.font.TextureFontRenderer.generateChars(TextureFontRenderer.scala:35) ~[opencomputers:MC1.16.5-1.8.5.3+0a4e918b6] {re:classloading}
	at li.cil.oc.client.renderer.font.DynamicFontRenderer.initialize(DynamicFontRenderer.scala:54) ~[opencomputers:MC1.16.5-1.8.5.3+0a4e918b6] {re:classloading}
	at li.cil.oc.client.renderer.font.DynamicFontRenderer.<init>(DynamicFontRenderer.scala:38) ~[opencomputers:MC1.16.5-1.8.5.3+0a4e918b6] {re:classloading}
	at li.cil.oc.client.renderer.TextBufferRenderCache$.<clinit>(TextBufferRenderCache.scala:16) ~[opencomputers:MC1.16.5-1.8.5.3+0a4e918b6] {re:classloading}
	at li.cil.oc.client.Proxy.$anonfun$init$2(Proxy.scala:98) ~[opencomputers:MC1.16.5-1.8.5.3+0a4e918b6] {re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:116) ~[?:?] {re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:103) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:306) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:997) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_412] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_412] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_412] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_412] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.42-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_412] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_412] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_412] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_412] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-prism-2024-02-29.jar:prism-2024-02-29] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 6.7.12-zen-g9298e1cd1f2a
	Java Version: 1.8.0_412, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1857417136 bytes (1771 MB) / 2151153664 bytes (2051 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 32
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.42-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.42-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.42-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.42-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.42-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.42
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		scorge@3.1.3
	Mod List: 
		forge-1.16.5-36.2.42-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.42-universal.jar                |Forge                         |forge                         |36.2.42             |SIDED_SETU|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		jei-1.16.5-7.8.0.1011.jar                         |Just Enough Items             |jei                           |7.8.0.1011          |SIDED_SETU|Manifest: NOSIGNATURE
		OpenComputers-MC1.16.5-1.8.5.3+0a4e918b6.jar      |OpenComputers                 |opencomputers                 |1.8.5.3             |SIDED_SETU|Manifest: NOSIGNATURE
	Crash Report UUID: ca7e5e88-c011-4a23-8d22-0b60e1b446c5
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 550.90.07, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 32x AMD Ryzen 9 7950X 16-Core Processor 
```

**Comment by RusticMaple** [comment]
when compiling myself it seems to work just fine so it might be an issue with me running it on linux like i said

**Comment by KosmosPrime** [comment]
That's because `ByteBuffer.rewind` doesn't exist yet in Java 8, there's only a `Buffer.rewind`. If you compile the code with a newer version (java 17, in my case) scalac will use the wrong one despite what's configured in the build script.
You can work around this by using at least Java 11 (which has the new method) or preferably Java 17 or better.

**Comment by RusticMaple** [comment]
That may be the case but it doesn't really help since Minecraft 1.16.5 only runs under Java 8 anyways.
Also like i said when i compile the mod myself it works just fine only when  i use the one under the release tab does it crash.

**Comment by TheRealM18** [comment]
You need Java 17 to run the 1.16.5 version.... I got the same error last night, and all I did was went to Java 17, and worked fine.

**Comment by TheRealM18** [comment]
also Minecraft does not check for java versions, so most is forward compatible.... like the 1.7.10 - 1.12.2 project of bring those versions to java 17 mods, and forge

**Comment by KosmosPrime** [comment]
I've opted to cast the relevant variable to to `Buffer` to work around this since there's only a few cases. If I've missed a case please do inform me (starting version 1.8.8).
